baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diegomarzo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Name of your site (displayed in the header)
name: Diego Marzo

# Short bio or description (displayed in the header)
description: A developer from a sunny place with a chihuahua

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/4606005?s=96&v=4

footer-links:
  github: diegomarzo
  linkedin: diego-marzo-3556221

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed